run:
  timeout: 5m
  skip-files:
    - ".*_gen\\.go"
    - ".*_test\\.go"
    - ".*\\.gen\\.go$"
  skip-dirs:
    - tests
    - .go
    - providers/binance/client

linters-settings:
  funlen:
    lines: 200
    statements: 75
  dupl:
    threshold: 700
  goconst:
    min-occurrences: 4
  exhaustive:
    default-signifies-exhaustive: true
linters:
  disable-all: true
  enable:
#    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace